name: 'olist_project'
version: '1.0.0'

profile: 'olist_project'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:       
  - "target"
  - "dbt_packages"



models:
  olist_project:         
    +schema: dimensional      
    +materialized: table      

    staging:                 
      +schema: cleaned       
      +materialized: view     

    intermediate:            
      +schema: cleaned        
      +materialized: table 

    dimensions: {}           
    marts: {}               



